version: '3.8'

services:
  app:
    image: node:20
    container_name: petbuddy_app
    working_dir: /src
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
    command: "npm start"
    networks:
      - petbuddy_network  

  redis:
    image: redis
    container_name: petbuddy_redis
    networks:
      - petbuddy_network  
    ports:
      - "6379:6379"

networks:
  petbuddy_network:
    driver: bridge
