version: '3.8'

services:
  app:
    image: bibisam06/petbuddy:server
    container_name: petbuddy_app
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - petbuddy_network  

  redis:
    image: redis
    container_name: petbuddy_redis
    ports:
      - "6379:6379"
    networks:
      - petbuddy_network  

networks:
  petbuddy_network:
    driver: bridge
